
DATA = 'data'
FEED = 'feed'
FEED_ITEMS = 'feed_items'

ID = 'id'
ID_DATA = 'Id'
AD = 'ad'
IMAGES = 'images'
IMAGE1 = 'Image1'
ROW3 = 'row_3'
SOURCE = 'src'
CITY ='city'
TYPE = 'type'
NO_WRITTERN = 'לא צויין'
KM = 'ק"מ'

AD_NUMBER = 'ad_number'
MANUFACTURER = 'manufacturer'
MODEL = 'model'
YEAR = 'year'
PRICE = 'price'
HAND = 'Hand_text'
CONTACT = 'contact_name'
